safe: true
markdown: kramdown
exclude: [ assets ]
permalink: /:title.html

default_theme: yandex
default_width: 792
default_lang: ru
default_body_class: list

kramdown:
  enable_coderay: false

presentation:
    title: Инструменты разработки мобильного фронтенда
    service: Мобилизация
    nda: false

author:
    name: Андрей Прокопюк

progress: true
